### ISSUE TITLE
`setupIcon` causes weird installer error messages.

### ISSUE THREAD

**Issue by jprichardson** [electron/windows-installer#119] opened 2016-07-22 02:12 UTC
This is an odd one. Built my windows installer on a `macOS` machine with `setupIcon` set causes the installer to display weird errors, despite successfully completing. This is reproducible 100% of the time in my case.

Versions:
- `macOS`: `10.11.5`
- `node`: `v6.1.0`
- `electron`: `v1.1.1`
- `wine`: `1.8.2`
- `winetricks`: `20160219 - sha1sum: 34401938dff575bbac6e19d62d0658c88a3ae502`
- `mono`: `4.2.3.4`

Code to build:

``` js
 import { createWindowsInstaller } from 'electron-winstaller'

  let resultPromise = createWindowsInstaller({
    appDirectory: config.getBuildSubDir('windows'),
    outputDirectory,
    authors: 'Exodus Movement Pte Ltd',
    exe: 'Exodus.exe',
    description: config.PACKAGE.description,
    iconUrl: 'https://www.exodus.io/favicon.ico',
   // if this is commented, no errors
    setupIcon: path.join(__dirname, '../../static/icons/ICO/exodus-icon.ico'),
    // setupExe: 'InstallExodus.exe'
    loadingGif: path.join(__dirname, '../../static/gifs/exodus-installer.gif')
  })
```

The install build process completes without any problems.

When installing the app on Windows, this error pops up twice:

![screen shot 2016-07-21 at 9 08 12 pm](https://cloud.githubusercontent.com/assets/150063/17044627/7e9dba38-4f87-11e6-98e8-e92c920fb296.png)

and contains a link to this: https://support.microsoft.com/en-us/kb/2715633 that has the following info:

> Shim errors for the .NET Framework version and platform support
> 
> Error: "You must enable the .NET Framework from the Windows Features dialog box"
> 
> This issue occurs because the app is not configured in a way that makes it possible to determine the appropriate version of the .NET Framework runtime. The corresponding shim code is SHIM_GOTO_CONTROLPANEL.

So I am assuming that maybe in the process of setting the icon, maybe other [PE](https://en.wikipedia.org/wiki/Portable_Executable) resources are getting destroyed that may indicate .NET version? IDK, but it's odd. Regardless though, the install still produces the desired outcome... links on desktop, start menu, installed to `%LocalAppData`, etc.

There are no errors in `SquirrelSetup.log`.

Any ideas? Thanks.

**Comment by swengorschewski** [comment] 2016-08-17 12:20
+1 :+1:

I have the same problem. 

Versions:

- winstaller 2.3.4
- linux: 4.6.4
- node: v6.3.0
- electron: v1.3.3
- wine: 1.8.2
- mono: 4.4.1

**Comment by hoffmabc** [comment] 2016-08-27 21:06
👍 Same here

**Comment by hoffmabc** [comment] 2016-08-27 21:06
I noticed that squirrel.exe also seems corrupt in the app folder.

**Comment by jprichardson** [comment] 2016-08-29 02:28
Any thoughts @paulcbetts on what may be causing this?

**Comment by MarshallOfSound** [comment] 2016-08-29 02:32
@jprichardson I just tested my windows build process on a macOS machine and it works flawlessly.  The only difference I can see in configs is that my setupIcon is a PNG and yours is an ICO.

I know the icons are set using `rcedit` which I remember caused people on macOS some issues a while back.  Perhaps try using a PNG to see if the problem can be isolated that way?

**Comment by paulcbetts** [comment] 2016-08-29 02:46
Use a Windows machine, or set up your build in AppVeyor

**Comment by jprichardson** [comment] 2016-08-29 02:49
@MarshallOfSound I tried the `.png` and the error I get is `Fatal error: Unable to set icon`.

@paulcbetts ok, thanks for chiming in.

**Comment by DoomyTheFroomy** [comment] 2016-11-02 07:56
👍 Same here

**Comment by bengotow** [comment] 2016-11-08 00:30
I've run into this as well. I think it might be appropriate to mention this in the README or remove the references to building from MacOS since this seems to be pretty consistent!

**Comment by dustinblackman** [comment] 2016-12-06 02:19
The issue seems to be with the bundled version of `rcedit.exe`. Using [`node-rcedit`](https://github.com/electron/node-rcedit) and it's bundled version on the final `Setup.Exe` solves the issue just fine.

**Comment by knuton** [comment] 2017-02-15 08:17
Thank you, @dustinblackman, I can confirm that setting the icon directly using node-rcedit works and does not corrupt `squirrel.exe`.

My hunch is that the problem has been fixed in electron/rcedit#26, which is being used in node-rcedit since electron/node-rcedit@73d4e74.

Maybe this package could use rcedit via node-rcedit? That would allow removing the duplicated logic for selecting Wine on non-Windows systems, and facilitate future updates of rcedit.

Other than this issue, building from Mac OS has worked just fine, so it would be great if it could be resolved!

**Comment by tjoye20** [comment] 2017-03-22 22:49
This issue fixed for me by just setting the icon while packing it, and not re-setting it when creating the installer.

**Comment by gossi** [comment] 2017-12-13 12:28
@tjoye20 how did you do that? Do you have some sample code?

**Comment by MarshallOfSound** [comment] 2018-03-27 10:56
Explained in #202

**Closed by MarshallOfSound** 2018-03-27 10:56 UTC

**Comment by iamisti** [comment] 2024-01-30 03:01
> Explained in #202

explained but not solved. Solution is to 'turn off the icon for the setup installer'.... thanks but that's exactly the feature I want to use.
